import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import './assets/css/select2.min.css'
import './assets/css/select2-bootstrap4.min.css'
import './assets/css/fontawesome/css/all.min.css'
import './assets/css/tempusdominus-bootstrap-4.min.css'
import './assets/css/OverlayScrollbars.min.css'
import './assets/css/adminlte.css'

import './assets/js/adminlte.js'
import './assets/js/select2.full.min.js'
import '../vue.config.js'
import 'bootstrap'
createApp(App).use(store).use(router).mount('#app')
